# Copyright (c) 2026 ZitaoTech
# SPDX-License-Identifier: MIT

description: BB Button to Arrow Key Input Processor

compatible: "zmk_bb_btn_to_arrow"

include: [base.yaml]

properties:
  "#input-processor-cells":
    type: int
    const: 0