# Copyright (c) 2023 ZitaoTech
# SPDX-License-Identifier: MIT

description: BB Trackball wheel-to-arrow key input processor
compatible = "zmk,input-processor";
include <zephyr/dt-bindings/input/input-event-codes.h>

/ {
    compatible = "zmk_bb_wheel_to_arrow";
    status = "okay";
};
